### create account + payload
POST http://localhost:3000/accounts HTTP/1.1
Content-Type: application/json

{
    "owner": "buurman",
    "currency": "USD"
}

### getaccount
GET http://localhost:3000/accounts/228

### list accounts
GET http://localhost:3000/accounts?page_id=1&page_size=10
